
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/../upload/image/original-image"
                    - "%kernel.project_dir%"


    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/../upload/"
                cache_prefix: "image"


    filter_sets:

        basic:
            quality: 30