apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: webserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: gcr.io/neural-sol-285619/github.com/aliomom/swap-time
          imagePullPolicy: Always
          name: php-apache
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: upload-persistent-storage
            mountPath: /var/www/upload
      volumes:
      - name: upload-persistent-storage
        persistentVolumeClaim:
          claimName: upload-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    run: web-service
  name: web-service
  namespace: default
spec:
  clusterIP: 10.0.9.235
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31609
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apache
  sessionAffinity: None
  type: LoadBalancer
