name: swaptime_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Localization Library
  flutter_localizations:
    sdk: flutter

  # DI
  provider: ^4.1.3

  # Dependency injection
  inject:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject

  # Camera
  camera: ^0.5.8+5

  # Video
  video_player: ^0.10.12

  # Paths
  path_provider: ^1.6.14

  # Shared Prefs
  shared_preferences: ^0.5.7+3

  # Network Agent
  http: ^0.12.1
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.7

  # Pair and Other Types
  analyzer_plugin: ^0.2.5

  # String validation
  validators: ^2.0.0+1

  # Retrofit
  retrofit: ^1.3.4

  # Logger
  logger: any

  # Streams and RX
  rxdart: ^0.24.1

  # ORM, Database SQL
  sqfentity: ^1.3.5+3

  # Firebase Libs
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.15
  firebase_remote_config: ^0.3.1+1
  cloud_firestore: ^0.13.7

  # Localization
  gen_lang: 0.1.3

  # Internationalization
  intl: ^0.16.1
  intl_translation: ^0.17.9
  intl_utils: ^1.6.3

  # Toasts
  fluttertoast: ^4.0.1

  # UUID
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3

  test: ^1.14.4

  inject_generator:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject_generator

  # Generate Language Files
  lang_table: 0.2.0

  # Icons Generator
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
